### PR TITLE
Updated upstream to 1.1.0

### PR DESCRIPTION
**Pull request by andras-tim**

### CODE REVIEW

**Comment by andras-tim** [comment]
After the successful merge, please release a new docker hub image with an individual tag.

**Comment by ruimarinho** [comment]
Thanks!

**Comment by ruimarinho** [comment]
I precipitated in this merge. The master version is ahead of 1.1.0 ([a23d13d](https://github.com/furlongm/openvpn-monitor/commit/a23d13db0b2ca4f79fe8fefb91459476bef0892f)). Please use that one instead.

**Comment by andras-tim** [comment]
I knew, but that has not been released yet. Do you want to be on the **master**?

**Pull request merged**
